# Generated by Django 5.2.7 on 2025-10-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_alter_resume_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, help_text='匹配度评分（0-100）')),
                ('summary', models.TextField(blank=True, help_text='简历内容摘要', null=True)),
                ('suggestions', models.TextField(blank=True, help_text='优化建议', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='resumes.resume')),
            ],
        ),
    ]
