# Generated by Django 5.2.7 on 2025-10-26 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/', verbose_name='简历文件')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='解析后的文本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '等待解析'), ('processing', '解析中'), ('done', '已经完成'), ('failed', '解析失败')], max_length=20, verbose_name='解析状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'db_table': 'resumes',
            },
        ),
    ]
