# Generated by Django 5.2.7 on 2025-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='解析后的文本'),
        ),
    ]
