# Generated by Django 5.2.7 on 2025-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='解析后的文本'),
        ),
    ]
