# Generated by Django 5.2.7 on 2025-11-04 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业院校')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='学习专业')),
                ('expected_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='期望岗位')),
                ('expected_salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='期望薪资')),
                ('expected_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='期望城市')),
                ('current_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='当前住址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户详细信息',
                'verbose_name_plural': '用户详细信息',
                'db_table': 'user_profiles',
            },
        ),
    ]
